name: Banking

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: hridoy
          POSTGRES_PASSWORD: "2543"
          POSTGRES_DB: go1
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432 # Forward the PostgreSQL port

    steps:
      - uses: actions/checkout@v2 # Use v2 instead of v3

      - name: Set up Go
        uses: actions/setup-go@v2 # Use v2 instead of v4
        with:
          go-version: "1.20"

      - name: Install PostgreSQL Client
        run: |
          sudo apt-get update
          sudo apt-get install postgresql-client

      - name: Install go-migrate
        run: |
         curl -L https://github.com/golang-migrate/migrate/releases/download/v4.16.2/migrate.linux-amd64.tar.gz | tar xvz
         sudo mv migrate /usr/bin/migrate
         which migrate


      - name: migrate db
        run: make mup

      - name: Test
        run: make test
